### ISSUE TITLE
Fix server.js error

### ISSUE THREAD

**Issue by camdzic** [Sapphire-Discord-Bot/images#1]
Hello, in the file "server.js" when you create an image, you create it from the bot property, which brings an error. The **storeImage** function is located in the utils.

Wrong code:
```js
let image = await bot.storeImage({
 buffer,
 mime: data.mimetype,
 request,
});
```

Fixed code:
```js
let image = await utils.storeImage({
 buffer,
 mime: data.mimetype,
 request,
});
```

**Comment by xgedev** [comment]
Thank you for bringing this up, I merged your PR.
